// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AutoTallerDbContext))]
    [Migration("20260528224221_AddPlacaVehiculo")]
    partial class AddPlacaVehiculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdRegistroAfectado")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoAccionAuditoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdTipoAccionAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoriaRepuesto", b =>
                {
                    b.Property<int>("IdCategoriaRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoriaRepuesto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdCategoriaRepuesto");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasRepuesto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodigoTelefono", b =>
                {
                    b.Property<int>("IdCodigoTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodigoTelefono"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdCodigoTelefono");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CodigosTelefono", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CorreoPersona", b =>
                {
                    b.Property<int>("IdCorreoPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCorreoPersona"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDominioCorreo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCorreo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCorreoPersona");

                    b.HasIndex("IdDominioCorreo");

                    b.HasIndex("IdPersona");

                    b.HasIndex("UsuarioCorreo", "IdDominioCorreo")
                        .IsUnique();

                    b.ToTable("CorreosPersona", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("IdFactura");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DetalleOrdenRepuesto", b =>
                {
                    b.Property<int>("IdDetalleOrdenRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleOrdenRepuesto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer");

                    b.Property<int>("IdRepuesto")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitarioAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdDetalleOrdenRepuesto");

                    b.HasIndex("IdRepuesto");

                    b.HasIndex("IdOrdenServicio", "IdRepuesto")
                        .IsUnique();

                    b.ToTable("DetalleOrdenRepuestos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DiagnosticoOrden", b =>
                {
                    b.Property<int>("IdDiagnosticoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDiagnosticoOrden"));

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hallazgos")
                        .HasColumnType("text");

                    b.Property<int>("IdMecanico")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text");

                    b.Property<string>("SintomasReportados")
                        .HasColumnType("text");

                    b.HasKey("IdDiagnosticoOrden");

                    b.HasIndex("IdMecanico");

                    b.HasIndex("IdOrdenServicio")
                        .IsUnique();

                    b.ToTable("DiagnosticosOrden", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DocumentoPersona", b =>
                {
                    b.Property<int>("IdDocumentoPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumentoPersona"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdDocumentoPersona");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdTipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("DocumentosPersona", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DominioCorreo", b =>
                {
                    b.Property<int>("IdDominioCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDominioCorreo"));

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDominioCorreo");

                    b.HasIndex("Dominio")
                        .IsUnique();

                    b.ToTable("DominiosCorreo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EstadoOrden", b =>
                {
                    b.Property<int>("IdEstadoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoOrden"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdEstadoOrden");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosOrden", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoOrden = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoOrden = 2,
                            Nombre = "En Proceso"
                        },
                        new
                        {
                            IdEstadoOrden = 3,
                            Nombre = "Completada"
                        },
                        new
                        {
                            IdEstadoOrden = 4,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            IdEstadoOrden = 5,
                            Nombre = "Recibido"
                        },
                        new
                        {
                            IdEstadoOrden = 6,
                            Nombre = "Diagnóstico en proceso"
                        },
                        new
                        {
                            IdEstadoOrden = 7,
                            Nombre = "Pendiente aprobación jefe"
                        },
                        new
                        {
                            IdEstadoOrden = 8,
                            Nombre = "Pendiente aprobación cliente"
                        },
                        new
                        {
                            IdEstadoOrden = 9,
                            Nombre = "Rechazado por cliente"
                        },
                        new
                        {
                            IdEstadoOrden = 10,
                            Nombre = "Aprobado parcial"
                        },
                        new
                        {
                            IdEstadoOrden = 11,
                            Nombre = "Aprobado total"
                        },
                        new
                        {
                            IdEstadoOrden = 12,
                            Nombre = "Reparación en proceso"
                        },
                        new
                        {
                            IdEstadoOrden = 13,
                            Nombre = "Listo para entrega"
                        },
                        new
                        {
                            IdEstadoOrden = 14,
                            Nombre = "Pendiente de pago"
                        },
                        new
                        {
                            IdEstadoOrden = 15,
                            Nombre = "Pagado"
                        },
                        new
                        {
                            IdEstadoOrden = 16,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            IdEstadoOrden = 17,
                            Nombre = "Cerrado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer");

                    b.Property<decimal>("ManoObra")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdOrdenServicio")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistorialPropietarioVehiculo", b =>
                {
                    b.Property<int>("IdHistorialPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialPropietario"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer");

                    b.HasKey("IdHistorialPropietario");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("HistorialPropietariosVehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MarcaVehiculo", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdMarca");

                    b.HasIndex("NombreMarca")
                        .IsUnique();

                    b.ToTable("MarcasVehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ModeloVehiculo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdModelo"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("integer");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdModelo");

                    b.HasIndex("IdTipoVehiculo");

                    b.HasIndex("IdMarca", "NombreModelo")
                        .IsUnique();

                    b.ToTable("ModelosVehiculo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrdenServicio", b =>
                {
                    b.Property<int>("IdOrdenServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrdenServicio"));

                    b.Property<string>("ComentarioCliente")
                        .HasColumnType("text");

                    b.Property<bool?>("CostoAprobado")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("CostoPropuesto")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("FechaDecisionCosto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstadoOrden")
                        .HasColumnType("integer");

                    b.Property<int>("IdMecanico")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("integer");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("integer");

                    b.Property<string>("NotaCostoPropuesto")
                        .HasColumnType("text");

                    b.Property<string>("TrabajoRealizado")
                        .HasColumnType("text");

                    b.HasKey("IdOrdenServicio");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoOrden");

                    b.HasIndex("IdMecanico");

                    b.HasIndex("IdTipoServicio");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("OrdenesServicio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Referencia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdOrdenServicio");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReparacionItem", b =>
                {
                    b.Property<int>("IdReparacionItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReparacionItem"));

                    b.Property<bool?>("AprobadoPorCliente")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AprobadoPorJefe")
                        .HasColumnType("boolean");

                    b.Property<string>("ComentarioCliente")
                        .HasColumnType("text");

                    b.Property<string>("ComentarioJefe")
                        .HasColumnType("text");

                    b.Property<decimal>("CostoEstimado")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("FechaDecisionCliente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDecisionJefe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HorasManoObraEstimada")
                        .HasColumnType("numeric");

                    b.Property<int?>("IdMecanico")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("IdReparacionItem");

                    b.HasIndex("IdMecanico");

                    b.HasIndex("IdOrdenServicio", "Orden")
                        .IsUnique();

                    b.ToTable("ReparacionesItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Repuesto", b =>
                {
                    b.Property<int>("IdRepuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRepuesto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdCategoriaRepuesto")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("IdRepuesto");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdCategoriaRepuesto");

                    b.ToTable("Repuestos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Mecánico"
                        },
                        new
                        {
                            IdRol = 3,
                            NombreRol = "Recepcionista"
                        },
                        new
                        {
                            IdRol = 4,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            IdRol = 5,
                            NombreRol = "JefeMecanicos"
                        },
                        new
                        {
                            IdRol = 6,
                            NombreRol = "JefeBodega"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TelefonoPersona", b =>
                {
                    b.Property<int>("IdTelefonoPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTelefonoPersona"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("IdCodigoTelefono")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdTelefonoPersona");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdCodigoTelefono", "NumeroTelefono")
                        .IsUnique();

                    b.ToTable("TelefonosPersona", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoAccionAuditoria", b =>
                {
                    b.Property<int>("IdTipoAccionAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoAccionAuditoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdTipoAccionAuditoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposAccionAuditoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoAccionAuditoria = 1,
                            Nombre = "Creación"
                        },
                        new
                        {
                            IdTipoAccionAuditoria = 2,
                            Nombre = "Actualización"
                        },
                        new
                        {
                            IdTipoAccionAuditoria = 3,
                            Nombre = "Eliminación"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdTipoDocumento");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("IdTipoServicio");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposServicio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoVehiculo", b =>
                {
                    b.Property<int>("IdTipoVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoVehiculo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdTipoVehiculo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposVehiculo", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoVehiculo = 1,
                            Nombre = "Sedán"
                        },
                        new
                        {
                            IdTipoVehiculo = 2,
                            Nombre = "Hatchback"
                        },
                        new
                        {
                            IdTipoVehiculo = 3,
                            Nombre = "SUV"
                        },
                        new
                        {
                            IdTipoVehiculo = 4,
                            Nombre = "Camioneta"
                        },
                        new
                        {
                            IdTipoVehiculo = 5,
                            Nombre = "Pickup"
                        },
                        new
                        {
                            IdTipoVehiculo = 6,
                            Nombre = "Motocicleta"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("IdModelo")
                        .HasColumnType("integer");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdModelo");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.Property<int>("RolesIdRol")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("RolesIdRol", "UsuariosIdUsuario");

                    b.HasIndex("UsuariosIdUsuario");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("Domain.Entities.TipoAccionAuditoria", null)
                        .WithMany()
                        .HasForeignKey("IdTipoAccionAuditoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Cliente", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.CorreoPersona", b =>
                {
                    b.HasOne("Domain.Entities.DominioCorreo", "DominioCorreo")
                        .WithMany()
                        .HasForeignKey("IdDominioCorreo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Persona", null)
                        .WithMany("CorreosPersona")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DominioCorreo");
                });

            modelBuilder.Entity("Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("Domain.Entities.Factura", null)
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DetalleOrdenRepuesto", b =>
                {
                    b.HasOne("Domain.Entities.OrdenServicio", null)
                        .WithMany()
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Repuesto", null)
                        .WithMany()
                        .HasForeignKey("IdRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DiagnosticoOrden", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Mecanico")
                        .WithMany()
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithOne("Diagnostico")
                        .HasForeignKey("Domain.Entities.DiagnosticoOrden", "IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Domain.Entities.DocumentoPersona", b =>
                {
                    b.HasOne("Domain.Entities.Persona", null)
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.HasOne("Domain.Entities.OrdenServicio", null)
                        .WithMany()
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.HistorialPropietarioVehiculo", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehiculo", null)
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ModeloVehiculo", b =>
                {
                    b.HasOne("Domain.Entities.MarcaVehiculo", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("IdTipoVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("Domain.Entities.OrdenServicio", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EstadoOrden", "EstadoOrden")
                        .WithMany()
                        .HasForeignKey("IdEstadoOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Mecanico")
                        .WithMany()
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("IdTipoServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoOrden");

                    b.Navigation("Mecanico");

                    b.Navigation("TipoServicio");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.HasOne("Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Pagos")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Domain.Entities.ReparacionItem", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Mecanico")
                        .WithMany()
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanico");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Domain.Entities.Repuesto", b =>
                {
                    b.HasOne("Domain.Entities.CategoriaRepuesto", "CategoriaRepuesto")
                        .WithMany()
                        .HasForeignKey("IdCategoriaRepuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaRepuesto");
                });

            modelBuilder.Entity("Domain.Entities.TelefonoPersona", b =>
                {
                    b.HasOne("Domain.Entities.CodigoTelefono", "CodigoTelefono")
                        .WithMany()
                        .HasForeignKey("IdCodigoTelefono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Persona", null)
                        .WithMany("TelefonosPersona")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodigoTelefono");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("Domain.Entities.ModeloVehiculo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("RolUsuario", b =>
                {
                    b.HasOne("Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Domain.Entities.OrdenServicio", b =>
                {
                    b.Navigation("Diagnostico");

                    b.Navigation("Pagos");

                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Navigation("CorreosPersona");

                    b.Navigation("TelefonosPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
